import { ROUTES } from ".";

export const MANAGE_REPORTS_ROUTES = {
  ELIGIBILITY_FILTER: `${ROUTES.MANAGE_REPORTS}/eligibility-filter`,
  GCONTRIBUTION_LIMITS: `${ROUTES.MANAGE_REPORTS}/gcontribution-limit`,
  CONTRIBUTION_LIMITS: `${ROUTES.MANAGE_REPORTS}/contribution-limit`,
  ELIGIBILITY_FORECAST: `${ROUTES.MANAGE_REPORTS}/eligibility-forecast`,
  DELETED_PARTICIPANT: `${ROUTES.MANAGE_REPORTS}/deleted-participant`,
  REHIRE_REPORT: `${ROUTES.MANAGE_REPORTS}/rehire-report`,
  NEW_PARTICIPANT: `${ROUTES.MANAGE_REPORTS}/new-participant`,
  EMPLOYEMENT_STATUS: `${ROUTES.MANAGE_REPORTS}/employement-status`,
};

export const MANAGE_REPORTS_MENU = [
  {
    label: "Report",
  },
  {
    label: "Eligibility",
    subNav: [
      {
        label: "Status",
        path: MANAGE_REPORTS_ROUTES.ELIGIBILITY_FILTER,
        contentHeader: "Reports",
        breadCrumbs: [],
        childRoutes: [],
      },
      {
        label: "Forecast",
        path: MANAGE_REPORTS_ROUTES.ELIGIBILITY_FORECAST,
        contentHeader: "Reports",
        breadCrumbs: [],
        childRoutes: [],
      },
    ],
    breadCrumbs: [],
    childRoutes: [],
  },
  {
    label: "Contribution Limits",
    subNav: [
      {
        label: "402 (G) Limit",
        path: MANAGE_REPORTS_ROUTES.GCONTRIBUTION_LIMITS,
        contentHeader: "Reports",
        breadCrumbs: [],
        childRoutes: [],
      },
      {
        label: "415",
        path: MANAGE_REPORTS_ROUTES.CONTRIBUTION_LIMITS,
        contentHeader: "Reports",
        breadCrumbs: [],
        childRoutes: [],
      },
    ],
    breadCrumbs: [],
    childRoutes: [],
  },
  {
    label: "Participant",
    subNav: [
      {
        label: "Deleted Participant",
        path: MANAGE_REPORTS_ROUTES.DELETED_PARTICIPANT,
        contentHeader: "Reports",
        breadCrumbs: [],
        childRoutes: [],
      },
      {
        id: "rehireReport",
        label: "Rehire Report",
        path: MANAGE_REPORTS_ROUTES.REHIRE_REPORT,
        contentHeader: "Reports",
        breadCrumbs: [],
        childRoutes: [],
      },
      {
        id: "newParticipant",
        label: "New Participant",
        path: MANAGE_REPORTS_ROUTES.NEW_PARTICIPANT,
        contentHeader: "Reports",
        breadCrumbs: [],
        childRoutes: [],
      },
    ],
    breadCrumbs: [],
    childRoutes: [],
  },
  {
    label: "Employment",
    subNav: [
      {
        label: "Status ",
        path: MANAGE_REPORTS_ROUTES.EMPLOYEMENT_STATUS,
        contentHeader: "Reports",
        breadCrumbs: [],
        childRoutes: [],
      },
    ],
    breadCrumbs: [],
    childRoutes: [],
  },
  {
    label: "Sponsor",
    path: MANAGE_REPORTS_ROUTES.ELIGIBILITY_FORECAST,
    contentHeader: "Reports",
    breadCrumbs: [],
    childRoutes: [],
  },
];

export const ALL_MANAGE_REPORTS_ROUTES = [
  ...MANAGE_REPORTS_MENU,
  {
    contentHeader: "Reports",
    path: MANAGE_REPORTS_ROUTES.ELIGIBILITY_FILTER,
    breadCrumbs: [
      // {
      //   label: "Manage Reports",
      //   link: MANAGE_REPORTS_ROUTES.ELIGIBILITY_FILTER,
      // },
    ],
  },
];
export const manageReportsFormNames = {
  ELIGIBILITY_FILTER: "eligibility filter",
  GCONTRIBUTION_LIMITS: "gcontribution limit",
  CONTRIBUTION_LIMITS: "contribution limit",
  ELIGIBILITY_FORECAST: "eligibility forecast",
  DELETED_PARTICIPANT: "deleted participant",
  REHIRE_REPORT: "rehire report",
  NEW_PARTICIPANT: "new participant",
  EMPLOYEMENT_STATUS: "employement status",
};

export const reportsFormFields = {
  [manageReportsFormNames.ELIGIBILITY_FILTER]: {
    search: "search",
    companyName: "companyName",
    companyId: "companyId",
    planId: "planId",
    planName: "planName",
    eligibilityStatus: "eligibilityStatus",
    planId: "planId",
    planName: "planName",
    ssn: "ssn",
    firstName: "firstName",
    lastName: "lastName",
    runDateFrom: "runDateFrom",
    runDateTo: "runDateTo",
    entryDateFrom: "entryDateFrom",
    entryDateTo: "entryDateTo",
    eligibilityStatus: "eligibilityStatus",
    sourceName: "sourceName",
    anchorFlag: "anchorFlag",
    eligibilityDateFrom: "eligibilityDateFrom",
    eligibilityDateTo: "eligibilityDateTo",
    reason: "reason",
  },
  [manageReportsFormNames.GCONTRIBUTION_LIMITS]: {
    nameOrSsn: "nameOrSsn",
    companyName: "companyName",
    companyId: "companyId",
    planId: "planId",
    planName: "planName",
    amountFrom: "amountFrom",
    amountTo: "amountTo",
    payDateFrom: "payDateFrom",
    payDateTo: "payDateTo",
    ssn: "ssn",
    firstName: "firstName",
    lastName: "lastName",
    preTaxTo: "preTaxTo",
    preTaxFrom: "preTaxFrom",
    dateFrom: "dateFrom",
    dateTo: "dateTo",
    ageFrom: "ageFrom",
    ageTo: "ageTo",
    rothFrom: "rothFrom",
    rothTo: "rothTo",
    totalContributionFrom: "totalContributionFrom",
    totalContributionTo: "totalContributionTo",
  },

  [manageReportsFormNames.CONTRIBUTION_LIMITS]: {
    nameOrSsn: "nameOrSsn",
    companyName: "companyName",
    companyId: "companyId",
    planId: "planId",
    planName: "planName",
    amountFrom: "amountFrom",
    amountTo: "amountTo",
    payDateFrom: "payDateFrom",
    payDateTo: "payDateTo",
    ssn: "ssn",
    firstName: "firstName",
    lastName: "lastName",
    preTaxTo: "preTaxTo",
    preTaxFrom: "preTaxFrom",
    afterTaxTo: "afterTaxTo",
    afterTaxFrom: "afterTaxFrom",
    matchFrom: "matchFrom",
    matchTo: "matchTo",
    nonElectiveFrom: "nonElectiveFrom",
    nonElectiveTo: "nonElectiveTo",
    RothFrom: "RothFrom",
    RothTo: "RothTo",
    TotalContributionFrom: "TotalContributionFrom",
    TotalContributionTo: "TotalContributionFrom",
  },
  [manageReportsFormNames.ELIGIBILITY_FORECAST]: {
    search: "search",
    companyName: "companyName",
    companyId: "companyId",
    planId: "planId",
    planName: "planName",
    asOfDate: "asOfDate",
    ssn: "ssn",
    firstName: "firstName",
    lastName: "lastName",
    sourceName: "sourceName",
    requirementMetDateFrom: "requirementMetDateFrom",
    requirementMetDateTo: "requirementMetDateTo",
    forecastedEntryDateFrom: "forecastedEntryDateFrom",
    forecastedEntryDateTo: "forecastedEntryDateTo",
    forecastedEntryDate: "forecastedEntryDate",
    eligibilityCriteria: "eligibilityCriteria",
  },
  [manageReportsFormNames.DELETED_PARTICIPANT]: {
    nameOrSsn: "nameOrSsn",
    companyId: "companyId",
    companyName: "companyName",
    fromDate: "fromDate",
    toDate: "toDate",
    ssn: "ssn",
    firstName: "firstName",
    lastName: "lastName",
    deletedBy: "deletedBy",
    deletedDateAndTimeFrom: "deletedDateAndTimeFrom",
    deletedDateAndTimeTo: "deletedDateAndTimeTo",
  },
  [manageReportsFormNames.REHIRE_REPORT]: {
    nameOrSsn: "nameOrSsn",
    companyId: "companyId",
    companyName: "companyName",
    fromDate: "fromDate",
    toDate: "toDate",
    planId: "planId",
    planName: "planName",
    ssn: "ssn",
    firstName: "firstName",
    lastName: "lastName",
    dateOfBirthFrom: "dateOfBirthFrom",
    dateOfBirthTo: "dateOfBirthTo",
    planId: "planId",
    planName: "planName",
    employmentStatus: "employmentStatus",
    dateOfHireFrom: "dateOfHireFrom",
    dateOfHireTo: "dateOfHireTo",
    recentTerminationDateFrom: "recentTerminationDateFrom",
    recentTerminationDateTo: "recentTerminationDateTo",
    recentRehireDateFrom: "recentRehireDateFrom",
    recentRehireDateTo: "recentRehireDateTo",
    eligibilityRequirementMetDateFrom: "eligibilityRequirementMetDateFrom",
    eligibilityRequirementMetDateTo: "eligibilityRequirementMetDateTo",
    eligibilityStatus: "eligibilityStatus",
    employeeClassification: "employeeClassification",
    planEntryDateFrom: "planEntryDateFrom",
    planEntryDateTo: "planEntryDateTo",
  },
  [manageReportsFormNames.NEW_PARTICIPANT]: {
    nameOrSsn: "nameOrSsn",
    companyId: "companyId",
    companyName: "companyName",
    fromDate: "fromDate",
    toDate: "toDate",
    payDateFrom: "payDateFrom",
    payDateTo: "payDateTo",
    ssn: "ssn",
    firstName: "firstName",
    lastName: "lastName",
    planId: "planId",
    planName: "planName",
    newToPlan: "newToPlan",
    eligibilityStatus: "eligibilityStatus",
    employeeClassification: "employeeClassification",
    address1: "address1",
    address2: "address2",
    address3: "address3",
    city: "city",
    state: "state",
    zipCode: "zipCode",
    email: "email",
    dateOfBirthFrom: "dateOfBirthFrom",
    dateOfBirthTo: "dateOfBirthTo",
    dateOfHireFrom: "dateOfHireFrom",
    dateOfHireTo: "dateOfHireTo",
    terminationDateFrom: "terminationDateFrom",
    terminationDateTo: "terminationDateTo",
    recentRehireDateFrom: "recentRehireDateFrom",
    recentRehireDateTo: "recentRehireDateTo",
    ineligibleSource: "ineligibleSource",
  },
  [manageReportsFormNames.EMPLOYEMENT_STATUS]: {
    nameOrSsn: "nameOrSsn",
    companyId: "companyId",
    companyName: "companyName",
    fromDate: "fromDate",
    planId: "planId",
    planName: "planName",
    ssn: "ssn",
    firstName: "firstName",
    lastName: "lastName",
    priorStatus: "priorStatus",
    updatedStatus: "updatedStatus",
    updatedDateTimeFrom: "updatedDateTimeFrom",
    updatedDateTimeTo: "updatedDateTimeTo",
  },
};
