const sourceData = [
  {
    label: "Employee Id",
    length: 15,
    dataType: "String",
    mandatory: true,
  },
  {
    label: "SSN",
    length: 15,
    dataType: "Number",
    mandatory: true,
  },
  {
    label: "RK Plan Number ",
    length: 15,
    dataType: "String",
    mandatory: false,
  },
  {
    label: "First Name",
    length: 50,
    dataType: "String",
    mandatory: true,
  },
  {
    label: "Middle Name",
    length: 50,
    dataType: "String",
    mandatory: false,
  },
  {
    label: "Last Name",
    length: 50,
    dataType: "String",
    mandatory: true,
  },
  {
    label: "Gender",
    length: 15,
    dataType: "String",
    mandatory: false,
  },

  {
    label: "Marital Status",
    length: 15,
    dataType: "String",
    mandatory: false,
  },
  {
    label: "Birth Date",
    length: 15,
    dataType: "Date",
    mandatory: false,
  },
  {
    label: "Address 1",
    length: 150,
    dataType: "String",
    mandatory: true,
  },
  {
    label: "Address 2",
    length: 150,
    dataType: "String",
    mandatory: false,
  },
  {
    label: "Address 3",
    length: 150,
    dataType: "String",
    mandatory: false,
  },
  {
    label: "City",
    length: 15,
    dataType: "String",
    mandatory: true,
  },
  {
    label: "Country",
    length: 15,
    dataType: "String",
    mandatory: true,
  },
  {
    label: "State",
    length: 15,
    dataType: "String",
    mandatory: true,
  },
  {
    label: "Zip code",
    length: 15,
    dataType: "String",
    mandatory: true,
  },
  {
    label: "Primary PHONE Number",
    length: 15,
    dataType: "String",
    mandatory: true,
  },
  {
    label: "Secondary PHONE Number",
    length: 15,
    dataType: "String",
    mandatory: false,
  },
  {
    label: "Primary email address",
    length: 50,
    dataType: "String",
    mandatory: false,
  },
  {
    label: "Hire Date",
    length: 50,
    dataType: "Date",
    mandatory: true,
  },
  {
    label: "Most Recent Term Date",
    length: 50,
    dataType: "Date",
    mandatory: true,
  },
  {
    label: "Most Recent Rehire",
    length: 50,
    dataType: "Date",
    mandatory: false,
  },
  {
    label: "Payroll Frequency ",
    length: 50,
    dataType: "String",
    mandatory: true,
  },
  {
    label: "HCE indicator",
    length: 50,
    dataType: "String",
    mandatory: false,
  },
  {
    label: "Employment status code",
    length: 15,
    dataType: "String",
    mandatory: true,
  },
  {
    label: "Pay Date ",
    length: 15,
    dataType: "Date",
    mandatory: true,
  },
  {
    label: "Leave Start Date ",
    length: 15,
    dataType: "Date",
    mandatory: false,
  },
  {
    label: "Leave End Date ",
    length: 15,
    dataType: "Date",
    mandatory: false,
  },
  {
    label: "Classification Name",
    length: 150,
    dataType: "String",
    mandatory: true,
  },
  {
    label: "Start Date ",
    length: 150,
    dataType: "Date",
    mandatory: false,
  },
  {
    label: "End Date ",
    length: 150,
    dataType: "Date",
    mandatory: false,
  },
];

const HoursAndCompensation = [
  {
    label: "Annual Salary ",
    length: 15,
    dataType: "Number",
    mandatory: false,
  },
  {
    label: "Gross Compensation ",
    length: 15,
    dataType: "Number",
    mandatory: false,
  },
  {
    label: "Plan Compensation ",
    length: 15,
    dataType: "Number",
    mandatory: false,
  },
  {
    label: "Hours",
    length: 15,
    dataType: "Number",
    mandatory: false,
  },
  {
    label: "Deferral %",
    length: 15,
    dataType: "Number",
    mandatory: false,
  },
  {
    label: "Match %",
    length: 15,
    dataType: "Number",
    mandatory: false,
  },
  {
    label: "RK Plan Number",
    length: 15,
    dataType: "String",
    mandatory: false,
  },
  {
    label: "Name",
    length: 50,
    dataType: "String",
    mandatory: false,
  },
  {
    label: "Amount",
    length: 15,
    dataType: "Number",
    mandatory: false,
  },
  {
    label: "RK Plan Number",
    length: 15,
    dataType: "String",
    mandatory: false,
  },
  {
    label: "LoanID",
    length: 15,
    dataType: "String",
    mandatory: false,
  },
  {
    label: "Loan Repayment ",
    length: 15,
    dataType: "Number",
    mandatory: false,
  },
];

export default sourceData;
