const data = [
  {
    field: "EMPLOYEE ID",
    value: "436",
    dataType: "Numeric",
    columnName: "Col A",
    selected: true,
  },
  {
    field: "SSN",
    value: "790015080",
    dataType: "Numeric",
    columnName: "Col B",
    selected: false,
  },
  {
    field: "FIRST NAME",
    value: "Marco",
    dataType: "String",
    columnName: "Col C",
    selected: false,
  },
  {
    field: "LAST NAME",
    value: "Parker",
    dataType: "String",
    columnName: "Col D",
    selected: false,
  },
  {
    field: "MIDDLE INITIAL",
    value: "A",
    dataType: "String",
    columnName: "Col E",
    selected: false,
  },
  {
    field: "PLAN COMPENSATION",
    value: "1000",
    dataType: "Numeric",
    columnName: "Col F",
    selected: false,
  },
  {
    field: "MARITAL STATUS",
    value: "M",
    dataType: "String",
    columnName: "Col G",
    selected: false,
  },
  {
    field: "BIRTH DATE",
    value: "1/1/2021",
    dataType: "Date",
    columnName: "Col H",
    selected: false,
  },
  {
    field: "FOREIGN ADDRESS INDICATOR",
    value: "N",
    dataType: "String",
    columnName: "Col I",
    selected: false,
  },
  {
    field: "ADDRESS 1",
    value: "3983 California Way",
    dataType: "String",
    columnName: "Col J",
    selected: false,
  },
  {
    field: "ADDRESS 2",
    value: "",
    dataType: "String",
    columnName: "Col K",
    selected: false,
  },
  {
    field: "EMPLOYEE ID",
    value: "436",
    dataType: "Numeric",
    columnName: "Col A",
    selected: false,
  },
  {
    field: "SSN",
    value: "790015080",
    dataType: "Numeric",
    columnName: "Col B",
    selected: false,
  },
  {
    field: "FIRST NAME",
    value: "Marco",
    dataType: "String",
    columnName: "Col C",
    selected: false,
  },
  {
    field: "LAST NAME",
    value: "Parker",
    dataType: "String",
    columnName: "Col D",
    selected: false,
  },
  {
    field: "MIDDLE INITIAL",
    value: "A",
    dataType: "String",
    columnName: "Col E",
    selected: false,
  },
  {
    field: "PLAN COMPENSATION",
    value: "1000",
    dataType: "Numeric",
    columnName: "Col F",
    selected: false,
  },
  {
    field: "MARITAL STATUS",
    value: "M",
    dataType: "String",
    columnName: "Col G",
    selected: false,
  },
  {
    field: "BIRTH DATE",
    value: "1/1/2021",
    dataType: "Date",
    columnName: "Col H",
    selected: false,
  },
  {
    field: "FOREIGN ADDRESS INDICATOR",
    value: "N",
    dataType: "String",
    columnName: "Col I",
    selected: false,
  },
  {
    field: "ADDRESS 1",
    value: "3983 California Way",
    dataType: "String",
    columnName: "Col J",
    selected: false,
  },
  {
    field: "ADDRESS 2",
    value: "",
    dataType: "String",
    columnName: "Col K",
    selected: false,
  },
];

export default data;
