export const allRecordReport = [
  { label: "EMPLOYEE ID", key: "employeeId" },
  { label: "SSN", key: "ssn" },
  { label: "PAY DATE", key: "payDate" },
  { label: "FIRST NAME", key: "firstName" },
  { label: "LAST NAME", key: "lastName" },
  { label: "MIDDLE INITIAL", key: "middleInitial" },
  { label: "GENDER", key: "gender" },
  { label: "MARITAL STATUS", key: "maritalStatus" },
  { label: "BIRTH DATE", key: "birthDate" },
  { label: "FOREIGN ADDRESS INDICATOR", key: "foreignAddressIndicator" },
  { label: "ADDRESS 1", key: "address1" },
  { label: "ADDRESS 2", key: "address2" },
  { label: "ADDRESS 3", key: "address3" },
  { label: "CITY", key: "city" },
  { label: "COUNTRY", key: "country" },
  { label: "STATE", key: "state" },
  { label: "ZIPCODE", key: "zipcode" },
  { label: "PRIMARY PHONE NUMBER", key: "primaryPhoneNumber" },
  { label: "SECONDARY PHONE NUMBER", key: "secondaryPhoneNumber" },
  { label: "PRIMARY EMAIL ADDRESS", key: "primaryEmailAddress" },
  { label: "HIRE DATE", key: "hireDate" },
  { label: "MOST RECENT TERM DATE", key: "mostRecentTermDate" },
  { label: "MOST RECENT REHIRE DATE", key: "mostRecentRehireDate" },
  { label: "PAYROLL FREQUENCY", key: "payrollFrequency" },
  { label: "TYC", key: "tyc" },
  { label: "TYC EFFECTIVE START DATE", key: "tycEffectiveStartDate" },
  { label: "TYC EFFECTIVE END DATE", key: "tycEffectiveEndDate" },
  { label: "LOCATION", key: "location" },
  {
    label: "LOCATION EFFECTIVE START DATE",
    key: "locationEffectiveStartDate",
  },
  { label: "LOCATION EFFECTIVE END DATE", key: "locationEffectiveEndDate" },
  { label: "DIVISION", key: "division" },
  {
    label: "DIVISION EFFECTIVE START DATE",
    key: "divisionEffectiveStartDate",
  },
  { label: "DIVISION EFFECTIVE END DATE", key: "divisionEffectiveEndDate" },
  { label: "DEPARTMENT", key: "department" },
  {
    label: "DEPARTMENT EFFECTIVE START DATE",
    key: "departmentEffectiveStartDate",
  },
  {
    label: "DEPARTMENT EFFECTIVE END DATE",
    key: "departmentEffectiveEndDate",
  },
  { label: "HCE INDICATOR", key: "hceIndicator" },
  { label: "EMPLOYMENT STATUS CODE", key: "employmentStatusCode" },
  { label: "LEAVE START DATE", key: "leaveStartDate" },
  { label: "LEAVE END DATE", key: "leaveEndDate" },
  { label: "GROSS COMPENSATION", key: "grossCompensation" },
  { label: "PLAN COMPENSATION", key: "planCompensation" },
  { label: "ANNUAL SALARY", key: "annualSalary" },
  { label: "HOURS", key: "hours" },
  {
    label: "SAMRK258_EMPLOYEE AFTER TAX",
    key: "samrk258_employeeAfterTax",
  },
  { label: "SAMRK258_MATCH SOURCE 1", key: "samrk258_matchSource1" },
  { label: "SAMRK258_MATCH SOURCE 2", key: "samrk258_matchSource2" },
  { label: "SAMRK258_MATCH SOURCE 3", key: "samrk258_matchSource3" },
  {
    label: "SAMRK259_EMPLOYEE AFTER TAX",
    key: "samrk259_employeeAfterTax",
  },
  { label: "SAMRK259_MATCH SOURCE 1", key: "samrk259_matchSource1" },
  { label: "SAMRK259_MATCH SOURCE 2", key: "samrk259_matchSource2" },
  { label: "SAMRK259_MATCH SOURCE 3", key: "samrk259_matchSource3" },
];

export const dataChangeReport = [
  { label: "RECORD", key: "record" },
  { label: "COMPANY NAME", key: "companyName" },
  { label: "EMPLOYEE ID", key: "employeeId" },
  { label: "SSN", key: "SSN" },
  { label: "FIRST NAME", key: "firstName" },
  { label: "LAST NAME", key: "lastName" },
  { label: "MIDDLE INITIAL", key: "middleInitial" },
  { label: "GENDER", key: "gender" },
  { label: "MARITAL STATUS", key: "maritalStatus" },
  { label: "BIRTH DATE", key: "birthDate" },
  { label: "FOREIGN ADDRESS INDICATOR", key: "foreignAddressIndicator" },
  { label: "ADDRESS 1", key: "address1" },
  { label: "ADDRESS 2", key: "address2" },
  { label: "ADDRESS 3", key: "address3" },
  { label: "CITY", key: "city" },
  { label: "COUNTRY", key: "country" },
  { label: "STATE", key: "state" },
  { label: "ZIP CODE", key: "zipcode" },
  { label: "PRIMARY PHONE NUMBER", key: "primaryPhoneNumber" },
  { label: "SECONDARY PHONE NUMBER", key: "secondaryPhoneNumber" },
  { label: "PRIMARY EMAIL ADDRESS", key: "primaryEmailAddress" },
  { label: "HIRE DATE", key: "hireDate" },
  { label: "MOST RECENT TERM DATE", key: "mostRecentTermDate" },
  { label: "MOST RECENT REHIRE DATE", key: "mostRecentRehireDate" },
  { label: "FREQUENCY", key: "payrollFrequency" },
  // { label: "TYC", key: "tyc" },
  // { label: "TYC EFFECTIVE START DATE", key: "tycEffectiveStartDate" },
  // { label: "TYC EFFECTIVE END DATE", key: "tycEffectiveEndDate" },
  { label: "LOCATION", key: "location" },
  {
    label: "LOCATION EFFECTIVE START DATE",
    key: "locationEffectiveStartDate",
  },
  { label: "LOCATION EFFECTIVE END DATE", key: "locationEffectiveEndDate" },
  // { label: "DIVISION", key: "division" },
  // {
  //   label: "DIVISION EFFECTIVE START DATE",
  //   key: "divisionEffectiveStartDate",
  // },
  // { label: "DIVISION EFFECTIVE END DATE", key: "divisionEffectiveEndDate" },
  // { label: "DEPARTMENT", key: "department" },
  // {
  //   label: "DEPARTMENT EFFECTIVE START DATE",
  //   key: "departmentEffectiveStartDate",
  // },
  // {
  //   label: "DEPARTMENT EFFECTIVE END DATE",
  //   key: "departmentEffectiveEndDate",
  // },
  { label: "HCE INDICATOR", key: "hceIndicator" },
  { label: "EMPLOYMENT STATUS CODE", key: "employmentStatusCode" },
  { label: "LEAVE START DATE", key: "leaveStartDate" },
  { label: "LEAVE END DATE", key: "leaveEndDate" },
];

export const dataOverrideReport = [
  { label: "RECORD", key: "record" },
  { label: "COMPANY NAME", key: "companyName" },
  { label: "EMPLOYEE ID", key: "employeeId" },
  { label: "SSN", key: "SSN" },
  { label: "FIRST NAME", key: "firstName" },
  { label: "LAST NAME", key: "lastName" },
  { label: "MIDDLE INITIAL", key: "middleInitial" },
  { label: "GENDER", key: "gender" },
  { label: "MARITAL STATUS", key: "maritalStatus" },
  { label: "BIRTH DATE", key: "birthDate" },
  { label: "FOREIGN ADDRESS INDICATOR", key: "foreignAddressIndicator" },
  { label: "ADDRESS 1", key: "address1" },
  { label: "ADDRESS 2", key: "address2" },
  { label: "ADDRESS 3", key: "address3" },
  { label: "CITY", key: "city" },
  { label: "COUNTRY", key: "country" },
  { label: "STATE", key: "state" },
  { label: "ZIPCODE", key: "zipcode" },
  { label: "PRIMARY PHONE NUMBER", key: "primaryPhoneNumber" },
  { label: "SECONDARY PHONE NUMBER", key: "secondaryPhoneNumber" },
  { label: "PRIMARY EMAIL ADDRESS", key: "primaryEmailAddress" },
  { label: "HIRE DATE", key: "hireDate" },
  { label: "MOST RECENT TERM DATE", key: "mostRecentTermDate" },
  { label: "MOST RECENT REHIRE DATE", key: "mostRecentRehireDate" },
  { label: "FREQUENCY", key: "payrollFrequency" },
  { label: "TYC", key: "tyc" },
  { label: "TYC EFFECTIVE START DATE", key: "tycEffectiveStartDate" },
  { label: "TYC EFFECTIVE END DATE", key: "tycEffectiveEndDate" },
  { label: "LOCATION", key: "location" },
  {
    label: "LOCATION EFFECTIVE START DATE",
    key: "locationEffectiveStartDate",
  },
  { label: "LOCATION EFFECTIVE END DATE", key: "locationEffectiveEndDate" },
  { label: "DIVISION", key: "division" },
  {
    label: "DIVISION EFFECTIVE START DATE",
    key: "divisionEffectiveStartDate",
  },
  { label: "DIVISION EFFECTIVE END DATE", key: "divisionEffectiveEndDate" },
  { label: "DEPARTMENT", key: "department" },
  {
    label: "DEPARTMENT EFFECTIVE START DATE",
    key: "departmentEffectiveStartDate",
  },
  {
    label: "DEPARTMENT EFFECTIVE END DATE",
    key: "departmentEffectiveEndDate",
  },
  { label: "HCE INDICATOR", key: "hceIndicator" },
  { label: "EMPLOYMENT STATUS CODE", key: "employmentStatusCode" },
  { label: "LEAVE START DATE", key: "leaveStartDate" },
  { label: "LEAVE END DATE", key: "leaveEndDate" },
];

export const errorValidationReport = [
  { label: "EMPLOYEE NAME", key: "employeeName" },
  { label: "SSN", key: "ssn" },
  { label: "PLAN ID", key: "planId" },
  { label: "PAY DATE", key: "paydate" },
  { label: "ERROR MESSAGE", key: "errors" },
  { label: "STATUS", key: "status" },
];
