import { ROUTES } from "./";

export const MANAGE_PAYROLL_ROUTES = {
  NEW_PAYROLL_UPLOAD: `${ROUTES.MANAGE_PAYROLL}/upload-file`,
  CREATE_OR_GENERATE: `${ROUTES.MANAGE_PAYROLL}/create-or-generate`,
  CREATE_PAYROLL_LISTING: `/create-payroll-listing`,
  UPLOADED_FILES_LISTING: `${ROUTES.PAYROLL}`,
  // PAYROLL_FILE_STATUS: `${ROUTES.MANAGE_PAYROLL}/payroll-file-status`,
};

export const MANAGE_PAYROLL_MENU = [
  {
    label: "Upload file",
    path: MANAGE_PAYROLL_ROUTES.NEW_PAYROLL_UPLOAD,
    contentHeader: "Payroll & Census Files",
    breadCrumbs: [],
    childRoutes: [],
  },
  {
    label: "Create or Generate",
    path: MANAGE_PAYROLL_ROUTES.CREATE_OR_GENERATE,
    contentHeader: "Payroll & Census Files",
    breadCrumbs: [],
    childRoutes: [],
  },
];

export const ALL_MANAGE_PAYROLL_ROUTES = [
  ...MANAGE_PAYROLL_MENU,
  {
    contentHeader: "Upload file",
    path: MANAGE_PAYROLL_ROUTES.NEW_PAYROLL_UPLOAD,
    breadCrumbs: [
      {
        label: "Payroll & Census Files",
        link: MANAGE_PAYROLL_ROUTES.NEW_PAYROLL_UPLOAD,
      },
    ],
  },
  {
    contentHeader: "Create or Generate",
    path: MANAGE_PAYROLL_ROUTES.CREATE_OR_GENERATE,
    breadCrumbs: [
      {
        label: "Payroll & Census Files",
        link: MANAGE_PAYROLL_ROUTES.CREATE_OR_GENERATE,
      },
    ],
  },
];

export const managePayrollFormNames = {
  PAYROLL_FILTER: "payroll filter",
  UPLOAD_FILE: "upload file",
  CREATE_OR_GENERATE_FILE: "create or generate file",
  EDIT_CONTRIBUTION: "edit contribution",
  EMPLOYEE_WIZARD: "employee wizard",
  ERROR_CORRECTION_FORM: "error_correction_form",
  FORFEITURE_FUNDING: "forfeiture_funding",
  CREATE_PAYROLL_LISTING: "create_payroll_listing",
};

export const payrollFormFields = {
  [managePayrollFormNames.PAYROLL_FILTER]: {
    companyId: "companyId",
    companyName: "companyName",
    planId: "planId",
    planName: "planName",
    rkPlanNumber: "rkPlanNumber",
    fileStatus: "fileStatus",
    fromDate: "fromDate",
    toDate: "toDate",
  },
  [managePayrollFormNames.UPLOAD_FILE]: {
    template: "fileType",
    uploadCensusAndPayroll: "uploadCensusAndPayroll",
    description: "description",
  },
  [managePayrollFormNames.CREATE_OR_GENERATE_FILE]: {
    companyId: "companyId",
    planId: "planId",
    payrollFrequencyId: "payrollFrequencyId",
    payDate: "payDate",
    description: "description",
  },
  [managePayrollFormNames.EDIT_CONTRIBUTION]: {
    afterTax: "afterTax",
    employerMatch: "employerMatch",
    nonElectiveContribution: "nonElectiveContribution",
    preTax: "preTax",
    roth: "roth",
    payPeriodHours: "payPeriodHours",
    Compensation: "Compensation",
    YTDhours: "YTDhours",
    YTDCompensation: "YTDCompensation",
    loanRepayment: "loanRepayment",
  },
  [managePayrollFormNames.EMPLOYEE_WIZARD]: {
    employeeFirstName: "employeeFirstName",
    employeeMiddleName: "employeeMiddleName",
    employeeLastName: "employeeLastName",
    socialSecurityNumber: "socialSecurityNumber",
    companyName: "companyName",
    employeeId: "employeeId",
    payrollFrequency: "payrollFrequency",
    gender: "gender",
    maritalStatus: "maritalStatus",
    email: "email",
    phoneNumber: "phoneNumber",
    addressName: "addressName",
    addressOne: "addressOne",
    addressTwo: "addressTwo",
    addressThree: "addressThree",
    city: "city",
    country: "country",
    state: "state",
    zipCode: "zipCode",
    additionalAddressName: "additionalAddressName",
    additionalAddressOne: "additionalAddressOne",
    additionalAddressTwo: "additionalAddressTwo",
    additionalAddressThree: "additionalAddressThree",
    additionalCity: "additionalCity",
    additionalForeignAddress: "additionalForeignAddress",
    additionalCountry: "additionalCountry",
    additionalState: "additionalState",
    additionalZipCode: "additionalZipCode",
    birthDate: "birthDate",
    hireDate: "hireDate",
    employmentStatus: "employmentStatus",
    mostRecentTermDate: "mostRecentTermDate",
    mostRecentRehireDate: "mostRecentRehireDate",
    classificationType: "classificationType",
    classificationCode: "classificationCode",
    classificationName: "classificationName",
    startDate: "startDate",
    endDate: "endDate",
    pendingQDRO: "pendingQDRO",
    ownership: "ownership",
    SSNofOwner: "SSNofOwner",
    returnMailIndicator: "returnMailIndicator",
    officer: "officer",
    HCE: "HCE",
    keyEmployee: "keyEmployee",
    restrictedEmployee: "restrictedEmployee",
  },
  [managePayrollFormNames.ERROR_CORRECTION_FORM]: {
    firstName: "firstName",
    middleName: "middleName",
    lastName: "lastName",
    gender: "gender",
    maritalStatus: "maritalStatus",
    birthDate: "birthDate",
    uniquePersonalIdentification: "uniquePersonalIdentification",
    primaryEmailAddress: "primaryEmailAddress",
    phone: "mobilePhoneNumber",
    city: "city",
    state: "state",
    stateId: "stateId",
    zipCode: "zipCode",
    mobilePhoneNumber: "mobilePhoneNumber",
    workPhoneNumber: "workPhoneNumber",
    address1: "address1",
    address2: "address2",
    address3: "address3",
    country: "country",
    hireDate: "hireDate",
    employmentStatusId: "employmentStatusId",
    employmentStatus: "employmentStatus",
    companyId: "companyId",
    employeeId: "employeeId",
    familyMemberOfOwner: "familyMemberOfOwner",
    employmentStatus: "employmentStatus",
    mostRecentTermDate: "terminationDate",
    rehireDate: "rehireDate",
    pendingQdro: "pendingQDROIndicator",
    officerIndicator: "officerIndicator",
    ownership: "ownership",
    familyOfOwener: "relationUniquePersonalIdentification",
    ssnOfOwner: "ssnOfOwner",
    returnMailIndicator: "returnMailIndicator",
    isOfficer: "isOfficer",
    isHCE: "hCEIndicator",
    isKeyEmployee: "keyEmployeeIndicator",
    restrictedEmployee: "insiderOrRestrictedEmployeeIndicator",
    companyName: "companyName",
    modeOfHours: "modeOfHours",
    annualSalary: "annualSalary",
    ytdHours: "ytdHours",
    payPeriodHours: "payPeriodHours",
    payrollFrequency: "payrollFrequency",
    payrollFrequencyId: "payrollFrequencyId",
    employeeNumber: "employeeNumber",

    compensationDetails: "compensations",
    contributionsDetails: "contributions",
    loanDetails: "loanDetails",
    errorReport: "errorReport",
    compensationDetailsRecordType: "compensationDetailsRecordType",
    paydate: "paydate",
    paydateContribution: "paydateContribution",
    paydateError: "paydateError",
    contributionDetailsRecordType: "contributionDetailsRecordType",
    errorReportRecordType: "errorReportRecordType",
  },
  [managePayrollFormNames.CREATE_PAYROLL_LISTING]: {
    id: "id",
    hours: "hours",
    planCompensation: "planCompensation",
    grossCompensation: "grossCompensation",
    contributions: "contributions",
  },
  [managePayrollFormNames.FORFEITURE_FUNDING]: {
    forfeitureType: "forfeitureType",
    forfeitureBalance: "forfeitureBalance",
    fundingAmount: "fundingAmount",
    fundingBank: "fundingBank",
    bankName: "bankName",
    fundingFileLevel: "fundingFileLevel",
    fundingPlanLevel: "fundingPlanLevel",
    fundingLocations: "fundingLocations",
  },
};

export const PAYROLL_RECORDS_TO_FETCH = 20;
