const data = [
  {
    field: "EMPLOYEE ID",
    value: "436",
    id: "11",
    dataType: "Numeric",
    columnName: "Col A",
    selected: true,
    filterSelect: false,
    firstchoice: "",
    selectedFilter: "",
  },
  {
    field: "SSN",
    value: "790015080",
    id: "1",
    dataType: "Numeric",
    columnName: "Col B",
    selected: false,
    filterSelect: false,
    firstchoice: "",
    selectedFilter: "",
  },
  {
    field: "FIRST NAME",
    value: "Marco",
    id: "2",
    dataType: "String",
    columnName: "Col C",
    selected: false,
    filterSelect: false,
    firstchoice: "",
    selectedFilter: "",
  },
  {
    field: "LAST NAME",
    value: "Parker",
    id: "3",
    dataType: "String",
    columnName: "Col D",
    selected: false,
    filterSelect: false,
    firstchoice: "",
    selectedFilter: "",
  },
  {
    field: "MIDDLE INITIAL",
    value: "A",
    id: "4",
    dataType: "String",
    columnName: "Col E",
    selected: false,
    filterSelect: false,
    firstchoice: "",
    selectedFilter: "",
  },
  {
    field: "PLAN COMPENSATION",
    value: "1000",
    id: "5",
    dataType: "Numeric",
    columnName: "Col F",
    selected: false,
    filterSelect: false,
    firstchoice: "",
    selectedFilter: "",
  },
  {
    field: "MARITAL STATUS",
    value: "M",
    id: "6",
    dataType: "String",
    columnName: "Col G",
    selected: false,
    filterSelect: false,
    firstchoice: "",
    selectedFilter: "",
  },
  {
    field: "BIRTH DATE",
    value: "1/1/2021",
    id: "7",
    dataType: "Date",
    columnName: "Col H",
    selected: false,
    filterSelect: false,
    firstchoice: "",
    selectedFilter: "",
  },
  {
    field: "FOREIGN ADDRESS INDICATOR",
    value: "N",
    id: "8",
    dataType: "String",
    columnName: "Col I",
    selected: false,
    filterSelect: false,
    firstchoice: "",
    selectedFilter: "",
  },
  {
    field: "ADDRESS 1",
    value: "3983 California Way",
    id: "9",
    dataType: "String",
    columnName: "Col J",
    selected: false,
    filterSelect: false,
    firstchoice: "",
    selectedFilter: "",
  },
  {
    field: "ADDRESS 2",
    value: "",
    id: "10",
    dataType: "String",
    columnName: "Col K",
    selected: false,
    filterSelect: false,
    firstchoice: "",
    selectedFilter: "",
  },
];

export default data;
